/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  alova_request: () => import("@/views/alova/request/index.vue"),
  alova_scenes: () => import("@/views/alova/scenes/index.vue"),
  alova_user: () => import("@/views/alova/user/index.vue"),
  "demo-route_child": () => import("@/views/demo-route/child/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  function_request: () => import("@/views/function/request/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  "function_toggle-auth": () => import("@/views/function/toggle-auth/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_permission: () => import("@/views/manage/permission/index.vue"),
  manage_student: () => import("@/views/manage/student/index.vue"),
  "manage_system-monitor": () => import("@/views/manage/system-monitor/index.vue"),
  manage_teacher: () => import("@/views/manage/teacher/index.vue"),
  "manage_user-behavior": () => import("@/views/manage/user-behavior/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  "multi-menu_first_child": () => import("@/views/multi-menu/first_child/index.vue"),
  "multi-menu_second_child_home": () => import("@/views/multi-menu/second_child_home/index.vue"),
  plugin_barcode: () => import("@/views/plugin/barcode/index.vue"),
  plugin_charts_antv: () => import("@/views/plugin/charts/antv/index.vue"),
  plugin_charts_echarts: () => import("@/views/plugin/charts/echarts/index.vue"),
  plugin_charts_vchart: () => import("@/views/plugin/charts/vchart/index.vue"),
  plugin_copy: () => import("@/views/plugin/copy/index.vue"),
  plugin_editor_markdown: () => import("@/views/plugin/editor/markdown/index.vue"),
  plugin_editor_quill: () => import("@/views/plugin/editor/quill/index.vue"),
  plugin_excel: () => import("@/views/plugin/excel/index.vue"),
  plugin_gantt_dhtmlx: () => import("@/views/plugin/gantt/dhtmlx/index.vue"),
  plugin_gantt_vtable: () => import("@/views/plugin/gantt/vtable/index.vue"),
  plugin_icon: () => import("@/views/plugin/icon/index.vue"),
  plugin_map: () => import("@/views/plugin/map/index.vue"),
  plugin_pdf: () => import("@/views/plugin/pdf/index.vue"),
  plugin_pinyin: () => import("@/views/plugin/pinyin/index.vue"),
  plugin_print: () => import("@/views/plugin/print/index.vue"),
  plugin_swiper: () => import("@/views/plugin/swiper/index.vue"),
  plugin_tables_vtable: () => import("@/views/plugin/tables/vtable/index.vue"),
  plugin_typeit: () => import("@/views/plugin/typeit/index.vue"),
  plugin_video: () => import("@/views/plugin/video/index.vue"),
  "pro-naive_form_basic": () => import("@/views/pro-naive/form/basic/index.vue"),
  "pro-naive_form_query": () => import("@/views/pro-naive/form/query/index.vue"),
  "pro-naive_form_step": () => import("@/views/pro-naive/form/step/index.vue"),
  "pro-naive_table_remote": () => import("@/views/pro-naive/table/remote/index.vue"),
  "pro-naive_table_row-edit": () => import("@/views/pro-naive/table/row-edit/index.vue"),
  "student_ai-tutor": () => import("@/views/student/ai-tutor/index.vue"),
  student_dashboard: () => import("@/views/student/dashboard/index.vue"),
  "student_learning-progress": () => import("@/views/student/learning-progress/index.vue"),
  student_tools: () => import("@/views/student/tools/index.vue"),
  teacher_analytics: () => import("@/views/teacher/analytics/index.vue"),
  teacher_assignment: () => import("@/views/teacher/assignment/index.vue"),
  teacher_course: () => import("@/views/teacher/course/index.vue"),
  teacher_dashboard: () => import("@/views/teacher/dashboard/index.vue"),
  teacher_student: () => import("@/views/teacher/student/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
