/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10,
      roles: ['R_ADMIN']
    }
  },
  {
    name: 'alova',
    path: '/alova',
    component: 'layout.base',
    meta: {
      title: 'alova',
      i18nKey: 'route.alova',
      icon: 'carbon:http',
      order: 7,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'alova_request',
        path: '/alova/request',
        component: 'view.alova_request',
        meta: {
          title: 'alova_request',
          i18nKey: 'route.alova_request',
          order: 1
        }
      },
      {
        name: 'alova_scenes',
        path: '/alova/scenes',
        component: 'view.alova_scenes',
        meta: {
          title: 'alova_scenes',
          i18nKey: 'route.alova_scenes',
          icon: 'cbi:scene-dynamic',
          order: 3
        }
      },
      {
        name: 'alova_user',
        path: '/alova/user',
        component: 'view.alova_user',
        meta: {
          title: 'alova_user',
          i18nKey: 'route.alova_user',
          icon: 'carbon:user-multiple',
          order: 2
        }
      }
    ]
  },
  {
    name: 'demo-route',
    path: '/demo-route',
    component: 'layout.base',
    meta: {
      title: 'demo-route',
      i18nKey: 'route.demo-route',
      hideInMenu: true,
      constant: true
    },
    children: [
      {
        name: 'demo-route_child',
        path: '/demo-route/child',
        component: 'view.demo-route_child',
        meta: {
          title: 'demo-route_child',
          i18nKey: 'route.demo-route_child',
          hideInMenu: true
        }
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 6,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child',
          icon: 'material-symbols:filter-list-off',
          order: 2
        },
        redirect: '/function/hide-child/one',
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one',
              icon: 'material-symbols:filter-list-off',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          multiTab: true,
          hideInMenu: true,
          activeMenu: 'function_tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request',
          icon: 'carbon:network-overlay',
          order: 3
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page',
          icon: 'ic:round-supervisor-account',
          order: 5,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab',
          order: 1
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth',
          icon: 'ic:round-construction',
          order: 4
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      roles: ['R_ADMIN', 'R_TEACHER', 'R_STUDENT']
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 2,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_permission',
        path: '/manage/permission',
        component: 'view.manage_permission',
        meta: {
          title: 'manage_permission',
          i18nKey: 'route.manage_permission',
          icon: 'ph:shield-checkered',
          order: 4,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_student',
        path: '/manage/student',
        component: 'view.manage_student',
        meta: {
          title: 'manage_student',
          i18nKey: 'route.manage_student'
        }
      },
      {
        name: 'manage_system-monitor',
        path: '/manage/system-monitor',
        component: 'view.manage_system-monitor',
        meta: {
          title: 'manage_system-monitor',
          i18nKey: 'route.manage_system-monitor',
          icon: 'ph:chart-line-up',
          order: 5,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_teacher',
        path: '/manage/teacher',
        component: 'view.manage_teacher',
        meta: {
          title: 'manage_teacher',
          i18nKey: 'route.manage_teacher'
        }
      },
      {
        name: 'manage_user-behavior',
        path: '/manage/user-behavior',
        component: 'view.manage_user-behavior',
        meta: {
          title: 'manage_user-behavior',
          i18nKey: 'route.manage_user-behavior',
          icon: 'ph:users-three',
          order: 6,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user-behavior'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      order: 8,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          order: 1
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          order: 2
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'plugin',
    path: '/plugin',
    component: 'layout.base',
    meta: {
      title: '插件示例',
      i18nKey: 'route.plugin',
      order: 7,
      icon: 'clarity:plugin-line',
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'plugin_barcode',
        path: '/plugin/barcode',
        component: 'view.plugin_barcode',
        meta: {
          title: 'plugin_barcode',
          i18nKey: 'route.plugin_barcode',
          icon: 'ic:round-barcode'
        }
      },
      {
        name: 'plugin_charts',
        path: '/plugin/charts',
        meta: {
          title: 'plugin_charts',
          i18nKey: 'route.plugin_charts',
          icon: 'mdi:chart-areaspline'
        },
        children: [
          {
            name: 'plugin_charts_antv',
            path: '/plugin/charts/antv',
            component: 'view.plugin_charts_antv',
            meta: {
              title: 'plugin_charts_antv',
              i18nKey: 'route.plugin_charts_antv',
              icon: 'hugeicons:flow-square'
            }
          },
          {
            name: 'plugin_charts_echarts',
            path: '/plugin/charts/echarts',
            component: 'view.plugin_charts_echarts',
            meta: {
              title: 'plugin_charts_echarts',
              i18nKey: 'route.plugin_charts_echarts',
              icon: 'simple-icons:apacheecharts'
            }
          },
          {
            name: 'plugin_charts_vchart',
            path: '/plugin/charts/vchart',
            component: 'view.plugin_charts_vchart',
            meta: {
              title: 'plugin_charts_vchart',
              i18nKey: 'route.plugin_charts_vchart',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_copy',
        path: '/plugin/copy',
        component: 'view.plugin_copy',
        meta: {
          title: 'plugin_copy',
          i18nKey: 'route.plugin_copy',
          icon: 'mdi:clipboard-outline'
        }
      },
      {
        name: 'plugin_editor',
        path: '/plugin/editor',
        meta: {
          title: 'plugin_editor',
          i18nKey: 'route.plugin_editor',
          icon: 'icon-park-outline:editor'
        },
        children: [
          {
            name: 'plugin_editor_markdown',
            path: '/plugin/editor/markdown',
            component: 'view.plugin_editor_markdown',
            meta: {
              title: 'plugin_editor_markdown',
              i18nKey: 'route.plugin_editor_markdown',
              icon: 'ri:markdown-line'
            }
          },
          {
            name: 'plugin_editor_quill',
            path: '/plugin/editor/quill',
            component: 'view.plugin_editor_quill',
            meta: {
              title: 'plugin_editor_quill',
              i18nKey: 'route.plugin_editor_quill',
              icon: 'mdi:file-document-edit-outline'
            }
          }
        ]
      },
      {
        name: 'plugin_excel',
        path: '/plugin/excel',
        component: 'view.plugin_excel',
        meta: {
          title: 'plugin_excel',
          i18nKey: 'route.plugin_excel',
          icon: 'ri:file-excel-2-line',
          keepAlive: true
        }
      },
      {
        name: 'plugin_gantt',
        path: '/plugin/gantt',
        meta: {
          title: 'plugin_gantt',
          i18nKey: 'route.plugin_gantt',
          icon: 'ant-design:bar-chart-outlined'
        },
        children: [
          {
            name: 'plugin_gantt_dhtmlx',
            path: '/plugin/gantt/dhtmlx',
            component: 'view.plugin_gantt_dhtmlx',
            meta: {
              title: 'plugin_gantt_dhtmlx',
              i18nKey: 'route.plugin_gantt_dhtmlx'
            }
          },
          {
            name: 'plugin_gantt_vtable',
            path: '/plugin/gantt/vtable',
            component: 'view.plugin_gantt_vtable',
            meta: {
              title: 'plugin_gantt_vtable',
              i18nKey: 'route.plugin_gantt_vtable',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_icon',
        path: '/plugin/icon',
        component: 'view.plugin_icon',
        meta: {
          title: 'plugin_icon',
          i18nKey: 'route.plugin_icon',
          localIcon: 'custom-icon'
        }
      },
      {
        name: 'plugin_map',
        path: '/plugin/map',
        component: 'view.plugin_map',
        meta: {
          title: 'plugin_map',
          i18nKey: 'route.plugin_map',
          icon: 'mdi:map'
        }
      },
      {
        name: 'plugin_pdf',
        path: '/plugin/pdf',
        component: 'view.plugin_pdf',
        meta: {
          title: 'plugin_pdf',
          i18nKey: 'route.plugin_pdf',
          icon: 'uiw:file-pdf'
        }
      },
      {
        name: 'plugin_pinyin',
        path: '/plugin/pinyin',
        component: 'view.plugin_pinyin',
        meta: {
          title: 'plugin_pinyin',
          i18nKey: 'route.plugin_pinyin',
          icon: 'entypo-social:google-hangouts'
        }
      },
      {
        name: 'plugin_print',
        path: '/plugin/print',
        component: 'view.plugin_print',
        meta: {
          title: 'plugin_print',
          i18nKey: 'route.plugin_print',
          icon: 'mdi:printer'
        }
      },
      {
        name: 'plugin_swiper',
        path: '/plugin/swiper',
        component: 'view.plugin_swiper',
        meta: {
          title: 'plugin_swiper',
          i18nKey: 'route.plugin_swiper',
          icon: 'simple-icons:swiper'
        }
      },
      {
        name: 'plugin_tables',
        path: '/plugin/tables',
        meta: {
          title: 'plugin_tables',
          i18nKey: 'route.plugin_tables',
          icon: 'icon-park-outline:table'
        },
        children: [
          {
            name: 'plugin_tables_vtable',
            path: '/plugin/tables/vtable',
            component: 'view.plugin_tables_vtable',
            meta: {
              title: 'plugin_tables_vtable',
              i18nKey: 'route.plugin_tables_vtable',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_typeit',
        path: '/plugin/typeit',
        component: 'view.plugin_typeit',
        meta: {
          title: 'plugin_typeit',
          i18nKey: 'route.plugin_typeit',
          icon: 'mdi:typewriter'
        }
      },
      {
        name: 'plugin_video',
        path: '/plugin/video',
        component: 'view.plugin_video',
        meta: {
          title: 'plugin_video',
          i18nKey: 'route.plugin_video',
          icon: 'mdi:video'
        }
      }
    ]
  },
  {
    name: 'pro-naive',
    path: '/pro-naive',
    component: 'layout.base',
    meta: {
      title: 'pro-naive',
      i18nKey: 'route.pro-naive',
      order: 7,
      icon: 'material-symbols-light:demography-outline-rounded',
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'pro-naive_form',
        path: '/pro-naive/form',
        meta: {
          title: 'pro-naive_form',
          i18nKey: 'route.pro-naive_form',
          icon: 'fluent:form-28-regular'
        },
        children: [
          {
            name: 'pro-naive_form_basic',
            path: '/pro-naive/form/basic',
            component: 'view.pro-naive_form_basic',
            meta: {
              title: 'pro-naive_form_basic',
              i18nKey: 'route.pro-naive_form_basic'
            }
          },
          {
            name: 'pro-naive_form_query',
            path: '/pro-naive/form/query',
            component: 'view.pro-naive_form_query',
            meta: {
              title: 'pro-naive_form_query',
              i18nKey: 'route.pro-naive_form_query'
            }
          },
          {
            name: 'pro-naive_form_step',
            path: '/pro-naive/form/step',
            component: 'view.pro-naive_form_step',
            meta: {
              title: 'pro-naive_form_step',
              i18nKey: 'route.pro-naive_form_step'
            }
          }
        ]
      },
      {
        name: 'pro-naive_table',
        path: '/pro-naive/table',
        meta: {
          title: 'pro-naive_table',
          i18nKey: 'route.pro-naive_table',
          icon: 'mynaui:table'
        },
        children: [
          {
            name: 'pro-naive_table_remote',
            path: '/pro-naive/table/remote',
            component: 'view.pro-naive_table_remote',
            meta: {
              title: 'pro-naive_table_remote',
              i18nKey: 'route.pro-naive_table_remote'
            }
          },
          {
            name: 'pro-naive_table_row-edit',
            path: '/pro-naive/table/row-edit',
            component: 'view.pro-naive_table_row-edit',
            meta: {
              title: 'pro-naive_table_row-edit',
              i18nKey: 'route.pro-naive_table_row-edit'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'student',
    path: '/student',
    component: 'layout.base',
    meta: {
      title: 'student',
      i18nKey: 'route.student',
      icon: 'mdi:school-outline',
      order: 1,
      roles: ['R_STUDENT']
    },
    redirect: '/student/dashboard',
    children: [
      {
        name: 'student_ai-tutor',
        path: '/student/ai-tutor',
        component: 'view.student_ai-tutor',
        meta: {
          title: 'student_ai-tutor',
          i18nKey: 'route.student_ai-tutor',
          icon: 'mdi:robot',
          order: 2
        }
      },
      {
        name: 'student_dashboard',
        path: '/student/dashboard',
        component: 'view.student_dashboard',
        meta: {
          title: 'student_dashboard',
          i18nKey: 'route.student_dashboard',
          icon: 'mdi:monitor-dashboard',
          order: 1
        }
      },
      {
        name: 'student_learning-progress',
        path: '/student/learning-progress',
        component: 'view.student_learning-progress',
        meta: {
          title: 'student_learning-progress',
          i18nKey: 'route.student_learning-progress',
          icon: 'mdi:chart-timeline-variant',
          order: 3
        }
      },
      {
        name: 'student_tools',
        path: '/student/tools',
        component: 'view.student_tools',
        meta: {
          title: 'student_tools',
          i18nKey: 'route.student_tools',
          icon: 'mdi:tools',
          order: 4
        }
      }
    ]
  },
  {
    name: 'teacher',
    path: '/teacher',
    component: 'layout.base',
    meta: {
      title: 'teacher',
      i18nKey: 'route.teacher',
      icon: 'mdi:school',
      order: 1,
      roles: ['R_TEACHER']
    },
    redirect: '/teacher/dashboard',
    children: [
      {
        name: 'teacher_analytics',
        path: '/teacher/analytics',
        component: 'view.teacher_analytics',
        meta: {
          title: 'teacher_analytics',
          i18nKey: 'route.teacher_analytics',
          icon: 'mdi:chart-line',
          order: 2
        }
      },
      {
        name: 'teacher_assignment',
        path: '/teacher/assignment',
        component: 'view.teacher_assignment',
        meta: {
          title: 'teacher_assignment',
          i18nKey: 'route.teacher_assignment',
          icon: 'mdi:file-document-edit',
          order: 3
        }
      },
      {
        name: 'teacher_course',
        path: '/teacher/course',
        component: 'view.teacher_course',
        meta: {
          title: 'teacher_course',
          i18nKey: 'route.teacher_course',
          icon: 'mdi:book-open-page-variant',
          order: 4
        }
      },
      {
        name: 'teacher_dashboard',
        path: '/teacher/dashboard',
        component: 'view.teacher_dashboard',
        meta: {
          title: 'teacher_dashboard',
          i18nKey: 'route.teacher_dashboard',
          icon: 'mdi:monitor-dashboard',
          order: 1
        }
      },
      {
        name: 'teacher_student',
        path: '/teacher/student',
        component: 'view.teacher_student',
        meta: {
          title: 'teacher_student',
          i18nKey: 'route.teacher_student',
          icon: 'mdi:account-group',
          order: 5
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
